//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardEVE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardEVE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #System
        ///Corporation
        ///Region
        ///Constellation
        ///Solar System
        ///Sun G5 (Yellow)
        ///Sun K7 (Orange)
        ///Sun K5 (Red Giant)
        ///Sun B0 (Blue)
        ///Sun F0 (White)
        ///Planet (Temperate)
        ///Planet (Ice)
        ///Planet (Gas)
        ///Moon
        ///Asteroid Belt
        ///Stargate (Caldari System)
        ///Stargate (Amarr Constellation)
        ///Plagioclase
        ///Spodumain
        ///Kernite
        ///Hedbergite
        ///Arkonor
        ///Cargo Container
        ///Ring
        ///Corpse
        ///Office Folder
        ///Office
        ///Factory Folder
        ///Credits
        ///Faction
        ///Tritanium
        ///Pyerite
        ///Mexallon
        ///Isogen
        ///Nocxium
        ///Zydrine
        ///Megacyte
        ///Garbage
        ///Spiced Wine
        ///Antibiotic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbonized Lead S
        ///Nuclear S
        ///Proton S
        ///Depleted Uranium S
        ///Titanium Sabot S
        ///Fusion S
        ///Phased Plasma S
        ///EMP S
        ///Carbonized Lead M
        ///Nuclear M
        ///Proton M
        ///Depleted Uranium M
        ///Titanium Sabot M
        ///Fusion M
        ///Phased Plasma M
        ///EMP M
        ///Carbonized Lead L
        ///Nuclear L
        ///Proton L
        ///Depleted Uranium L
        ///Titanium Sabot L
        ///Fusion L
        ///Phased Plasma L
        ///EMP L
        ///Mjolnir Cruise Missile
        ///Scourge Cruise Missile
        ///Inferno Cruise Missile
        ///Nova Cruise Missile
        ///Nova Heavy Missile
        ///Mjolnir Heavy Missile
        ///Inferno Heavy Missile
        ///Scourge Heavy Mis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
    }
}
